### ISSUE TITLE
Issue with lazy loading.

### ISSUE THREAD

**Issue by tianyi-wang-rockalltech** [koleary94/Angular-2-Datepicker#24]
Got this error when using this component in a module which is being lazy loaded by the router.

`Error: Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.`

Use it in `App.module.ts` works. I think he problem is caused here by:
https://angular.io/docs/ts/latest/cookbook/ngmodule-faq.html#!#q-browser-vs-common-module

I am not sure if `BrowserModule` is needed here https://github.com/koleary94/Angular-2-Datepicker/blob/master/src/datepicker.module.ts#L12 

Maybe `CommonModule` can be used instead?

**Comment by koleary94** [comment]
hey @tianyi-wang-rockalltech. thanks for doing research into this! Don't have time to address this today but i'll check out and merge the associated pr tomorrow

**Comment by koleary94** [comment]
hey @tianyi-wang-rockalltech. just released your fix in v`0.4.0`. let me know if it solves your problem

**Comment by tianyi-wang-rockalltech** [comment]
@koleary94 cheers, updated to 0.4, everything works fine. :+1:
