### ISSUE TITLE
.setDate should reset text if !value

### ISSUE THREAD

**Issue by alexbyk** [koleary94/Angular-2-Datepicker#27]
I tried to use this component, but it's impossible to "clear" a date. Instead of that datepicker always shows current date.

Maybe setDate() should clear the text if passed argument is falsy?

**Comment by koleary94** [comment]
hey @alexbyk. i'm going to be out this weekend, but i'll implement the ability to clear the date on monday. thanks for bringing it to my attention!

**Comment by koleary94** [comment]
hey @alexbyk. check out the [latest version](https://github.com/koleary94/Angular-2-Datepicker/releases/latest). let me know if that solves your problems.

**Comment by alexbyk** [comment]
thanks)))

**Comment by rajsibi7** [comment]
sorry, i can't find how to clear the date?
