### ISSUE TITLE
readonly attribute into directive

### ISSUE THREAD

**Issue by Herzenkin** [koleary94/Angular-2-Datepicker#28]
Hi!

Is it possible to make datepicker input field readonly? If not, would you be so kind as to add such attribute?

**Comment by koleary94** [comment]
Hey @Herzenkin! I'll add that attribute in the next release. Should get to that tonight.

**Comment by Herzenkin** [comment]
Cool! Will wait for it!

**Comment by koleary94** [comment]
Hey @Herzenkin. you can pass in `[disabled]="true"` in the [latest release](https://github.com/koleary94/Angular-2-Datepicker/releases/tag/v0.5.0). let me know if that works!

**Comment by Herzenkin** [comment]
@koleary94  now it works! Thanx a lot!

**Comment by Farooq-ThinkDigital** [comment]
hi koleary94 : can we do readonly for hour and minute.
