### ISSUE TITLE
System JS config

### ISSUE THREAD

**Issue by AAAnderson7301** [koleary94/Angular-2-Datepicker#31]
Hey do you have an example of using this with system js?

**Comment by AAAnderson7301** [comment]
Please ignore the above question I was able to figure out the configuration however I am having an issue using it within my forms. Here is an example ``` <material-datepicker id="expense_date{{i}}" class="form-control" [(ngModel)]="expense.Date"  name="date{{i}}" ></material-datepicker> ```  I am getting a console error ```No value accessor for form control with name: 'date0'``` It seems my name tag is getting cleared out.

**Comment by koleary94** [comment]
hey @AAAnderson7301. did you get your second comment figured out?
