### ISSUE TITLE
Does the datepicker take this: 2015-06-29T00:00:00

### ISSUE THREAD

**Issue by largeDachshund** [koleary94/Angular-2-Datepicker#32]
My model is passing this date: 2015-06-29T00:00:00 to 
`<material-datepicker [(date)]="activeLeaseDetails.endDate" dateFormat="MM-DD-YYYY"></material-datepicker>`

Now, when it does, this is what I get:

![image](https://cloud.githubusercontent.com/assets/7054672/19793803/4c07dfe2-9c83-11e6-984c-0335f88d9217.png)

If I'm not supposed to send a date like, "2015-06-29T00:00:00", could you explain what the date should look like?

Thanks!

**Comment by alexbyk** [comment]
@largeDachshund 

The `date` property is supposed to be an instance of a `Date` object, created like this `new Date()` you can check an example of usage [here](https://github.com/koleary94/Angular-2-Datepicker/blob/master/integration-test/app.component.ts)

You're trying to pass a string. Convert it to `Date`

**Comment by largeDachshund** [comment]
Thanks for the quick reply!  That's an indispensable tip!

**Comment by largeDachshund** [comment]
Just in case another poor soul comes across this issue, I'll explain the source of "2015-06-29T00:00:00".  That's the date coming from .Net/SQL Server in json.  Even though I'm using TypeScript, this value is being passed to my date variable!  Gotta love that!  So to get a proper date this is what i did:
`activeLeaseDetails.endDate = new Date(data.endDate);`

That seemed to do the trick.  Thanks, @alexbyk !

**Comment by koleary94** [comment]
thanks @alexbyk!
