### ISSUE TITLE
Go back many years

### ISSUE THREAD

**Issue by guillermo-serfe** [koleary94/Angular-2-Datepicker#34]
Is there another way to go back many years instead clicking month by month?

For example, if I need to set a date of the year 1985, I need to go back one month at a time until I arrive to that year?

Thanks!

**Comment by koleary94** [comment]
hey @guillermo-serfe . That functionality currently doesn't exist. i'll add it this weekend!

**Comment by guillermo-serfe** [comment]
Hi @koleary94, thanks for the feedback! 

Do you have any updates on this? Sorry for the hurry, but I need this functionality for the project where I'm working on.

I really like the work that you did with this date-picker and it would be a shame to have to change it.

I await your response.
Thanks a lot!

**Comment by koleary94** [comment]
Hey @guillermo-serfe ! Sorry for the late reply. I've been pretty busy at work. Haven't finished it yet, but the current progress is in [this branch](https://github.com/koleary94/Angular-2-Datepicker/compare/change-year). I'm going to release it by the end of wednesday (I'm in PST timezone). The gameplan is to allow the user to select the month as well, but for the sake of time i'll release that in `0.7.0`  :smile:

**Comment by koleary94** [comment]
Hi @guillermo-serfe . run `npm install angular2-material-datepicker@next` when you have a chance! All of the functionality is there for changing the year. I just want to refactor a little bit more and refine the design before I make an official release. The code is still in the same branch that I linked above.

**Comment by guillermo-serfe** [comment]
Hi @koleary94, I tested it and it works! There's only one visual detail, I can't see the month (it gets out of the dropdown window), but I guess this detail enters on the refactoring.

Thanks a lot for your fast work, it's an awesome job.  ;)

**Comment by koleary94** [comment]
no problem @guillermo-serfe ! can you send me a pic of not seeing the month? I can't seem to reproduce it on chrome, safari, or firefox

**Comment by guillermo-serfe** [comment]
@koleary94 Sorry for the late reply, I was busy working on the weekend. I had a custom style on my component that was crushing the date-picker style.

So it works! I've updated it on my project. Sorry for the inconvenience.

Thanks!

**Comment by guillermo-serfe** [comment]
Hi @koleary94, Sorry to bother you again. I need to format the date on Angular 2 date pipe default (for example: Dec 10, 2016). Is too much if I ask to you to add that date format? Or I don't know if you can allow us to edit parameter [inputText], so we can set the format as we want when (dateChanged) is triggered. 

I await your response.

Thank you again!

**Comment by koleary94** [comment]
@guillermo-serfe haha no worries man. For the sake of backwards compatibility and modularity, I went the route of allowing `dateFormat` to be _either_ a `string` or a `function`. I updated the readme to clarify. Going to make an official release soon; just want to get some tests up and running first. Reinstall `@next` when you have a chance :)

**Comment by guillermo-serfe** [comment]
@koleary94 it works perfect! I've updated it on my project.

I really appreciate your help. Thanks a lot!

**Comment by guillermo-serfe** [comment]
Hi @koleary94, I'm using this beta version and works perfect. 

I just wanted to make a suggestion for the official release: 
A more user friendly design would be add arrows to select months and other arrows (and existing input) to select years.

Regards.

**Comment by ireade** [comment]
Hi @koleary94 , really great work on this! I was just wondering when this feature would be pushed to the official release?
